apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: pipelines
  namespace: <your-namespace>
spec:
  apiServer:
    deploy: true
    enableSamplePipeline: false
  database:
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
  objectStorage:
    minio:
      deploy: true
      bucket: mlpipeline
      image: quay.io/opendatahub/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance
      pvcSize: 10Gi
  persistenceAgent:
    deploy: true
  scheduledWorkflow:
    deploy: true
