apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kfp-pvc-1
  namespace: <your-namespace>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi
