apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kfp-pvc-1
  labels:
    app: pytorch-training
    demo: runai-to-kfp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
